version: "3.9"
services:
  postgres:
    image: docker.io/postgres:16
    environment:
      - POSTGRES_USER=temporal
      - POSTGRES_PASSWORD=temporal
      - POSTGRES_DB=temporal
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U temporal"]
      interval: 3s
      timeout: 5s
      retries: 10

  temporal:
    image: docker.io/temporalio/auto-setup:1.24.2
    depends_on:
      - postgres
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgres
      - DISABLE_ES=true # no Elasticsearch
    ports:
      - "7233:7233" # Temporal gRPC

  temporal-ui:
    image: docker.io/temporalio/ui:2.30.1
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_UI_PORT=8080
      # ↓ allow CSRF cookie on http (dev)
      - TEMPORAL_CSRF_COOKIE_INSECURE=true
    ports:
      - "8080:8080" # Web UI at http://localhost:8080

